### ISSUE TITLE
经过测试满星并未生效，技能应该是部分改了二倍获取，攻速生效但好像没啥大用，定怪生效，移速没测应该生效伤害没敢开。

### ISSUE THREAD

**Issue by 200433zc** [JMBQ/URC#1]
总结：还是无法快乐乐土，建议技能奔放一点满星修复下。完毕

**Comment by JMBQ** [comment]
我觉得你可能没勾选满星
![00](https://user-images.githubusercontent.com/78288131/209895148-f0a96801-9484-4790-9073-70e847bf968c.jpg)

**Comment by JMBQ** [comment]
想奔放就开降龙，当然了，你都奔放了，是否安全就无所谓了

**Comment by AV179464** [comment]
一定要有zygisk吗？，我hidemagisk打开软件会闪退

**Comment by JMBQ** [comment]
> 一定要有zygisk吗？，我hidemagisk打开软件会闪退

一定要，如果是app原因，会有闪退字符串写在app上，截图看下
