### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by DogeStyle69** [JMBQ/URC#11]
crash on sony xz3 android 10

**Comment by DogeStyle69** [comment]
1.3.9 works fine before on xz3

**Comment by JMBQ** [comment]
> crash on sony xz3 android 10

Provide U.R.C home screenshots and log screenshots

**Comment by DogeStyle69** [comment]
This information is generated from the Crash Log View application. - https://play.google.com/store/apps/details?id=com.arumcomm.crashlogviewer

Process: com.JMBQ.URC
PID: 26671
UID: 10369
Flags: 0x20a8be44
Package: com.JMBQ.URC v141 (1.4.1)
Foreground: Yes
Build: Sony/801SO/801SO:10/52.1.D.0.178/052001D000017800726438165:user/release-keys
UUID: 12c8537f-54d9-45a0-8df7-d0d4c232b236

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Sony/801SO/801SO:10/52.1.D.0.178/052001D000017800726438165:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-07-25 22:54:48+0700
pid: 26671, tid: 27162, name: Thread-3  >>> com.JMBQ.URC <<<
uid: 10369
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7428f507d8
Cause: execute-only (no-read) memory access error; likely due to data in .text.
    x0  0000000000000001  x1  000000742d62a108  x2  000000733f0f9d60  x3  000000733f0fa020
    x4  000000733f0f9d60  x5  0000007428f54bec  x6  000000733f0f9d50  x7  7f7f7f7f7f7f7f7f
    x8  0000007428f507d8  x9  0a9add4871da2a0f  x10 0000000000000000  x11 00000000d61f0000
    x12 0000000000004100  x13 0000000001380000  x14 000000733dffb6f8  x15 000000000000000b
    x16 0000007428f63b18  x17 0000007428f005a4  x18 00000000a3014314  x19 000000739fc3b600
    x20 000000733ce73000  x21 000000733dffd020  x22 000000739e88c37c  x23 0000007396e732a7
    x24 0000000000000019  x25 000000739e88c38c  x26 000000733dffd020  x27 000000733dffb930
    x28 0000000000000000  x29 000000733dffb830
    sp  000000733dffb7a0  lr  000000733ce4a83c  pc  000000733ce4ece0

backtrace:
      #00 pc 000000000001cce0  [anon:.bss]

**Comment by DogeStyle69** [comment]
![ezgif-4-6b5191e63c](https://github.com/JMBQ/URC/assets/134132868/ad5d1beb-c6a4-4507-a84e-9bd06f919bf0)

**Comment by JMBQ** [comment]
> ![ezgif-4-6b5191e63c](https://github.com/JMBQ/URC/assets/134132868/ad5d1beb-c6a4-4507-a84e-9bd06f919bf0)
> 

are you using an emulator？
Isn't it a real phone?

**Comment by DogeStyle69** [comment]
im using scrcpy to remote my phone and record it using obs

**Comment by JMBQ** [comment]
version 1.4.1?
It might detect something before crashing

**Comment by DogeStyle69** [comment]
> version 1.4.1? It might detect something before crashing

yap, 1.4.0 crash too
