### ISSUE TITLE
软件闪退问题

### ISSUE THREAD

**Issue by jiellll1219** [JMBQ/URC#15]
手机为小米mix2s，系统为国内版MIUI 12.5.1.0 稳定版 android10，使用Magisk Delta，已将软件添加超级用户列表白名单，已开启Zygisk并按照视频重启，具体表现为：打开软件后不到一秒闪退，无root请求弹窗，多次尝试结果均为闪退。
附闪退前截图：
![IMG_20230812_165501](https://github.com/JMBQ/URC/assets/61046104/884f8716-558d-48c6-bb8a-d722af4b8466)

我另一部无法root的手机小米mix2使用国内版MIUI 11 9.10.24 开发版 android9可正常打开软件

**Comment by JMBQ** [comment]
# URC启动时将检查
* 自身运行环境是否处于64位(arm64-v8a)
* 自身是否处于被调试状态
* 自身完整性，对抗过签名

  
可能性大概这些，需要自行排查

**Comment by SeeMi157** [comment]
哥们你解决了吗
