### ISSUE TITLE
一直提示'No zygisk process found'

### ISSUE THREAD

**Issue by MrtHmk** [JMBQ/URC#16]
如题，是哪里出问题了，需要怎么解决

**Comment by MrtHmk** [comment]
是Shamiko版本过低的原因吗

**Comment by JMBQ** [comment]
你面具的设置问题

**Comment by MrtHmk** [comment]
设置的话应该是没问题的，我用Magisk26.1时可以正常运行，而用Magisk Delta的时候就提示'No zygisk process found'
我认为可能是因为Magisk Delta和URC插件不兼容的原因

**Comment by JMBQ** [comment]
delta是可以正常用的，关键是你的delta设置

**Comment by JMBQ** [comment]
你只需要开启zygisk，让这个进程出现，具体怎么做，谷歌或者请教这方面的人
