### ISSUE TITLE
Bad guy detected

### ISSUE THREAD

**Issue by Marc067** [JMBQ/URC#19]
I dont know whats wrong. I already install shamiko, configure denylist the game. But everytime i try to activate the hack it always says "Bad guy detected" something like that.

**Comment by JMBQ** [comment]
There are some bad guys on your device, such as gameguardian. URC does not check the application package name, but determines it based on their actual function.

**Comment by Marc067** [comment]
> 

I see. It works now. Thank you 🙏

**Comment by Marc067** [comment]
Can i ask too how to use LK/super damage?

**Comment by JMBQ** [comment]
#7

**Comment by Marc067** [comment]
> #7

One more thing. Im sorry for asking many question but i really want to use LK damage. Can you give example of numbers to change in config? Because no matter what i change in "config=" there is no changes in damage. Or am i doing it wrong?

**Comment by JMBQ** [comment]
only a example

config=1111166150

**Comment by Marc067** [comment]
> only an example
> 
> config=1111166150

Not really working for me T.T still thank you for your assistance 🙏
