### ISSUE TITLE
Nox 9的URC不停要求重啓

### ISSUE THREAD

**Issue by ryu-jp** [JMBQ/URC#2]
你好，我在Nox 9裝上了面具，給了URC權限，教學影片上的黑名單操作都全做了，URC還是要我重啓，重啓後又是重啓，可以怎解決嗎，謝謝

**Comment by JMBQ** [comment]
URC仅仅支持在真机上运行，原则上是不支持模拟器的

不停重启是因为没有成功刷入模块，你可以手动强制模块测试后续步骤，模块就在apk里

**Comment by ryu-jp** [comment]
謝謝, 我不太會androidh的開發,怎樣手动强制模块测试?
在apk里模块怎提出來?

**Comment by JMBQ** [comment]
解压，不用试了，会崩

**Comment by ryu-jp** [comment]
謝謝，現在用模擬器的有什麼方法可修改，看到你另一個git的最新apk不支援模擬器了

**Comment by JMBQ** [comment]
> 謝謝，現在用模擬器的有什麼方法可修改，看到你另一個git的最新apk不支援模擬器了

你可以尝试releases 1.1.0，这个版本支持模拟器

**Comment by sherlokcerry** [comment]
您好！请问您一下，若想在个人电脑上游玩可修改的国服，目前有什么可行的方法吗？

**Comment by JMBQ** [comment]
> 您好！请问您一下，若想在个人电脑上游玩可修改的国服，目前有什么可行的方法吗？

你可以尝试gg修改器

**Comment by sherlokcerry** [comment]
> > 您好！请问您一下，若想在个人电脑上游玩可修改的国服，目前有什么可行的方法吗？
> 
> 你可以尝试gg修改器，另外我还提供了6.4版本的国服直装破解版，手机使用

谢谢您的回复！再请问一下如何进行签名，我使用MT管理器因为没有会员不能自定义签名，谢谢！

**Comment by JMBQ** [comment]
> > > 您好！请问您一下，若想在个人电脑上游玩可修改的国服，目前有什么可行的方法吗？
> > 
> > 你可以尝试gg修改器，另外我还提供了6.4版本的国服直装破解版，手机使用
> 
> 谢谢您的回复！我下载了6.4直装版于真机。再请问一下如何进行签名？我使用的MT管理器因为没有会员不能自定义签名，谢谢！

不需要会员也可以签名，或者使用np管理器自定义签名

**Comment by sherlokcerry** [comment]
> > > > 您好！请问您一下，若想在个人电脑上游玩可修改的国服，目前有什么可行的方法吗？
> > > 
> > > 
> > > 你可以尝试gg修改器，另外我还提供了6.4版本的国服直装破解版，手机使用
> > 
> > 
> > 谢谢您的回复！我下载了6.4直装版于真机。再请问一下如何进行签名？我使用的MT管理器因为没有会员不能自定义签名，谢谢！
> 
> 不需要会员也可以签名，或者使用np管理器自定义签名

非常抱歉，我对于安卓逆向不了解，np管理器使用没什么经验，并不知道如何自定义签名，在np管理器中找到“直装版apk”后，选择了“功能”，“APK签名”，“导入签名”，“生成密钥”把sign文件里的内容在每一栏都粘贴了，用这样的方法有了对应内容的签名密钥，确定后生成的apk可以安装但是会闪退，请问我的操作在哪里就出错了？能请您指正一下吗？谢谢！

**Comment by JMBQ** [comment]
能安装就证明签名方法正确。
你是要对我的直装破解版重新签名吗，那闪退是正常的，因为有我自己的签名检验

**Comment by sherlokcerry** [comment]
> 能安装就证明签名方法正确。 你是要对我的直装破解版重新签名吗，那闪退是正常的，因为有我自己的签名检验

不是，在安装直装版后打开游戏开启MOD会显示“sign check fail”,导致无法使用MOD，所以我想知道是不是我应该对安装包做些什么操作，您的视频教程我有看，不知道哪个是对应直装版的，真抱歉耽误您时间来回复。

**Comment by JMBQ** [comment]
> > 能安装就证明签名方法正确。 你是要对我的直装破解版重新签名吗，那闪退是正常的，因为有我自己的签名检验
> 
> 不是，在安装直装版后打开游戏开启MOD会显示“sign check fail”,导致无法使用MOD，所以我想知道是不是我应该对安装包做些什么操作，您的视频教程我有看，不知道哪个是对应直装版的，真抱歉耽误您时间来回复。

压缩包里有个文档，打开复制字符串，然后打开游戏悬浮窗，有个sign的东西，输入进去确定就完事了

**Comment by sherlokcerry** [comment]
> > > 能安装就证明签名方法正确。 你是要对我的直装破解版重新签名吗，那闪退是正常的，因为有我自己的签名检验
> > 
> > 
> > 不是，在安装直装版后打开游戏开启MOD会显示“sign check fail”,导致无法使用MOD，所以我想知道是不是我应该对安装包做些什么操作，您的视频教程我有看，不知道哪个是对应直装版的，真抱歉耽误您时间来回复。
> 
> 压缩包里有个文档，打开复制字符串，然后打开游戏悬浮窗，有个sign的东西，输入进去确定就完事了

oh！看到了，谢谢！直装版相较于其他版本只有两个功能是出于反作弊的考虑吗？

**Comment by JMBQ** [comment]
> > > > 能安装就证明签名方法正确。 你是要对我的直装破解版重新签名吗，那闪退是正常的，因为有我自己的签名检验
> > > 
> > > 
> > > 不是，在安装直装版后打开游戏开启MOD会显示“sign check fail”,导致无法使用MOD，所以我想知道是不是我应该对安装包做些什么操作，您的视频教程我有看，不知道哪个是对应直装版的，真抱歉耽误您时间来回复。
> > 
> > 压缩包里有个文档，打开复制字符串，然后打开游戏悬浮窗，有个sign的东西，输入进去确定就完事了
> 
> oh！看到了，谢谢！直装版相较于其他版本只有两个功能是出于反作弊的考虑吗？

😄，这问题角度很特别，纯粹是当时懒得去获取其他功能地址而已，无CD千万别滥用就好，滥用就可能嗝屁

**Comment by sherlokcerry** [comment]
> > > > > 能安装就证明签名方法正确。 你是要对我的直装破解版重新签名吗，那闪退是正常的，因为有我自己的签名检验
> > > > 
> > > > 
> > > > 不是，在安装直装版后打开游戏开启MOD会显示“sign check fail”,导致无法使用MOD，所以我想知道是不是我应该对安装包做些什么操作，您的视频教程我有看，不知道哪个是对应直装版的，真抱歉耽误您时间来回复。
> > > 
> > > 
> > > 压缩包里有个文档，打开复制字符串，然后打开游戏悬浮窗，有个sign的东西，输入进去确定就完事了
> > 
> > 
> > oh！看到了，谢谢！直装版相较于其他版本只有两个功能是出于反作弊的考虑吗？
> 
> 😄，这问题角度很特别，纯粹是当时懒得去获取其他功能地址而已，无CD千万别滥用就好，滥用就可能嗝屁

谢谢！
