### ISSUE TITLE
Game detects injection

### ISSUE THREAD

**Issue by SerjoHacks** [JMBQ/URC#20]
Hello, after some small update in honkai. The game sees the injection and a sign appears asking you to remove third-party software (the version is still the same 6.9.0) Same with the mod menu. I hope you can fix this soon.

**Comment by JMBQ** [comment]
This is caused by the official remote update of the defense strategy, which cannot be updated quickly. I recommend using URC to replace the menu module. You can use it even if your phone dont rooted.
