### ISSUE TITLE
Detect some bad guys

### ISSUE THREAD

**Issue by queenalex0** [JMBQ/URC#22]
I have uninstalled gameguardian and lucky patcher but i am still getting detect some bad guys what can i do?

**Comment by JMBQ** [comment]
phone restart

**Comment by queenalex0** [comment]
> phone restart

just did that no change

**Comment by JMBQ** [comment]
This means that there are still programs injecting URC, please check

**Comment by queenalex0** [comment]
> This means that there are still programs injecting URC, please check

like what apps?

**Comment by Jordan231111** [comment]
Always detect badguys on vphone gaga android 10

**Comment by JMBQ** [comment]
> Always detect badguys on vphone gaga android 10

Then why can URC be used normally on my vphonegaga android 10?
