### ISSUE TITLE
升级到zygisknext后提示 No Zygisk process found

### ISSUE THREAD

**Issue by MisakaOne** [JMBQ/URC#23]
如图
![Screenshot_2023-10-29-00-21-55-372_com JMBQ URC](https://github.com/JMBQ/URC/assets/108571772/04feba29-ef65-4050-8740-8f91e367047e)
![Screenshot_2023-10-29-00-24-44-891_me weishu kernelsu](https://github.com/JMBQ/URC/assets/108571772/8e91108b-98e0-4948-9324-0d6e0c54aeac)
zygisknext 是最新的zygiskonkernelsu

**Comment by JMBQ** [comment]
描述清晰，有图佐证
这个问题将在143版本修复
URC将不再查询Zygisk进程，只认模块运行状态
预计半个月内发布

**Comment by MisakaOne** [comment]
加密修改了吗

**Comment by JMBQ** [comment]
> 加密修改了吗

什么

**Comment by MisakaOne** [comment]
开启LK的加密

**Comment by JMBQ** [comment]
自行摸索
