### ISSUE TITLE
7.00版本 我一进行修改游戏就闪退 如何处理比较好

### ISSUE THREAD

**Issue by a540205820** [JMBQ/URC#24]
7.00版本 我一进行修改游戏就闪退 如何处理比较好.
上传了图片和视频再看看。

**Comment by JMBQ** [comment]
![199.jpg](https://github.com/JMBQ/URC/assets/78288131/07f2faa8-0526-41d7-b790-6b86464fe866)

**Comment by a540205820** [comment]
https://github.com/JMBQ/URC/assets/148414819/4fb41d01-1786-4342-a33a-83cbd8db188f

![微信图片_20231104104602](https://github.com/JMBQ/URC/assets/148414819/96e1a459-f875-400f-a227-1374d3c0619b)
![微信图片_20231104104611](https://github.com/JMBQ/URC/assets/148414819/363f1054-511e-474b-b577-9a95c4727d48)
![微信图片_20231104104612](https://github.com/JMBQ/URC/assets/148414819/59e198da-2fe7-4030-b4a1-318ae9838774)
视频和图片都上传，麻烦再看下。

**Comment by JMBQ** [comment]
第二次提供的信息量就能清楚了解问题了。
修改是成功的，我重复你的操作流程没有出现闪退，进入八重村闲逛战斗都没问题，判定你的闪退不是修改引起的。

你可以检查这些：
如果不修改，重复视频里的操作是否闪退？

是否是设备剩余运存不足导致游戏闪退？

是否已经设置过shamiko，对游戏隐藏root？虽然检查到root应该是弹窗提醒，但我毕竟几个版本没玩了，不了解

最后，你的设备有点跟不上这游戏了，闪退也不意外，最好能换个更强的设备，我以前有个破手机，强行提api，测试urc，崩三闪退是日常

**Comment by a540205820** [comment]
1.不修改，运行流场不闪退。
2.运存不足 这个还真不太清楚。
3.shamiko这个是按照你视频里面勾选配置排除列表进行设置的，没问题。
4.设备确实有点久了。。

**Comment by JMBQ** [comment]
我重新梳理了源码，大概找到问题所在了
模块确实多占用了额外的运存
这是因为制做镜像引起的，忘记释放了

**Comment by a540205820** [comment]
> 我重新梳理了源码，大概找到问题所在了 模块确实多占用了额外的运存 这是因为制做镜像引起的，忘记释放了

哦 我来再试试看

**Comment by a540205820** [comment]
还是闪退，看来是我不配用外挂 ￣□￣｜｜
