### ISSUE TITLE
关于崩坏3国际服卡载入游戏

### ISSUE THREAD

**Issue by lzq960605** [JMBQ/URC#26]
你在pmt发的安装包版本，还是URC进入到登录界面登录后，登录后会卡在触摸任意处进入游戏，点了后卡住一会就还是在触摸任意处进入游戏，在谷歌市场下载的也是一样，不知道咋回事，屏蔽检测也试了

**Comment by JMBQ** [comment]
登陆上了账号，就是进不去游戏，是吧？
网络问题用梯子解决

**Comment by lzq960605** [comment]
用梯子一样，是卡在触摸任意处进入游戏，然后你再点击又会卡在这里，进不去游戏

**Comment by JMBQ** [comment]
这就是网络问题，梯子不行就换
