### ISSUE TITLE
在0.7.6版本的KernelSU上无法获取到SU权限

### ISSUE THREAD

**Issue by rurudo-AI** [JMBQ/URC#28]
![Screenshot_2024-01-21-00-21-22-520_me weishu kernelsu](https://github.com/JMBQ/URC/assets/37221092/0db7d271-c704-4c59-b403-165da4061981)
![Screenshot_2024-01-21-00-21-36-649_com JMBQ URC](https://github.com/JMBQ/URC/assets/37221092/adc84173-014d-47b9-9068-2de19f9c28d5)

**Comment by JMBQ** [comment]
第4个框框告诉了我，你没有给它开白名单
和德尔塔一个道理，urc看不到su，申请su就无从谈起

**Comment by JMBQ** [comment]
> > 第4条框架告诉我,你没有给它开白名 和德尔塔一个道理,看看没有,申请就没开始
> 
> 但是同样的设置在0.7.5上就没有问题
> ![Screenshot_2024-01-21-11-27-00-112_com brave browser_nightly-edit](https://github.com/JMBQ/URC/assets/37221092/72cb5330-36ef-427f-8f45-092e9c7cbd23)
> ![Screenshot_2024-01-21-11-28-30-363_me weishu kernelsu](https://github.com/JMBQ/URC/assets/37221092/1b849618-9521-49bc-93c1-b74bcbcf24c5)
> 不管是开启还是关闭 都获取不到su
> 应该是这个问题吧https://github.com/tiann/KernelSU/commit/e934bfb64850ef1584d7920eab3dbf53507b3bd8

我不清楚ksu，但原因已经说了，urc被屏蔽了su，就如同银行app被屏蔽了无法检测su一样，所以无法申请su，自行解决
