### ISSUE TITLE
未通过校验怎么整

### ISSUE THREAD

**Issue by 205539940** [JMBQ/URC#32]

**Comment by JMBQ** [comment]
详细描述+截图，我有设置过这个？

**Comment by 205539940** [comment]
![Screenshot_2024-03-11-16-45-23-431_com.JMBQ.URC.jpg](https://github.com/JMBQ/URC/assets/116540633/e6478ed4-bdf6-49f6-8e17-6ebb937e0a54)

打开崩三，然后urc选择崩三进程，然后扭转万象。过一会就显示这个。崩三没有效果

**Comment by JMBQ** [comment]
使用145，同时主页截图看下，不要遮挡

**Comment by 205539940** [comment]
![Screenshot_2024-03-11-18-45-19-711_com.JMBQ.URC.jpg](https://github.com/JMBQ/URC/assets/116540633/82e4253e-af94-4374-99cf-d91d185fb4e3)

是145

**Comment by JMBQ** [comment]
卸载app，重新安装

**Comment by 205539940** [comment]
![Screenshot_2024-03-12-00-18-41-333_com.JMBQ.URC.jpg](https://github.com/JMBQ/URC/assets/116540633/47ceb71c-55e0-4249-9613-1e289c5cf498)

卸载重装好像还是不行。跟之前一样。对了还提示了detect some bad guys

**Comment by 205539940** [comment]
![Screenshot_2024-03-12-00-21-04-201_io.github.huskydg.magisk.jpg](https://github.com/JMBQ/URC/assets/116540633/22cd0317-d7f9-4595-a298-bb602dc4d152)

也配置了排除列表

**Comment by JMBQ** [comment]
问答栏有答案
