### ISSUE TITLE
bad guy

### ISSUE THREAD

**Issue by pokemc32ryan** [JMBQ/URC#36]
作者，你寫到提示bad guys是框架工具被發現，到底是被哪個應用發現，是都要隱藏嗎？

**Comment by pokemc32ryan** [comment]
直接把LSposed關了也一樣～

**Comment by JMBQ** [comment]
我很尊重lsposed，绝对不会去检测它
我盲猜你安装了gg
有些人开了urc的满星，然后又开脚本倍攻去刷钻，被封之后，跑去mega那诉苦，神烦，所以直接检测gg这种修改器

**Comment by pokemc32ryan** [comment]
感謝，我試試

**Comment by pokemc32ryan** [comment]
可以了～
