### ISSUE TITLE
大佬7.7版本功能失效了

### ISSUE THREAD

**Issue by qq2687089026** [JMBQ/URC#38]
7.7版本开始移速.坚韧.能量.都失效了希望大佬能
![Screenshot_2024-08-23-03-39-39-62_bb14a71b88daec8919abdc0d162ceaa8](https://github.com/user-attachments/assets/d884de09-b201-4d1c-ae38-09c228176ce6)
修复。

**Comment by hshq31** [comment]
+1，日志上修改成功后面是空白的

**Comment by JMBQ** [comment]
米贼在推进方法inline，导致hook原方法不会生效

满星攻速无法被inline，应该会持续生效

我在问答栏里说过，只要有人能绕过urc签名检验，我就更新一次urc

没人绕过就随缘更新
