### ISSUE TITLE
期望可以支持 kernelsu 的 SU 实现

### ISSUE THREAD

**Issue by fatinghenji** [JMBQ/URC#4]
如题，kernel su 项目地址：https://github.com/tiann/KernelSU
在 kernelsu 中给于 U.R.C root 权限，软件中依旧提示 magisk_su_failed

**Comment by fatinghenji** [comment]
补充说明：kernel su 可以安装并正常使用 zygisk

**Comment by JMBQ** [comment]
140会修复这些问题，只判断纯粹的su，缺点是可能无法一键安装模块。

我在MEGA群里说了，无论任何人，只要他能修改139的APK文件且安装后依旧能正常实现功能，视为爆破成功，那我将在半个月内更新140并添加“退图”功能。
如果没人爆破，140不添加任何功能，只修复bug，年底更新
