### ISSUE TITLE
6.70闪退

### ISSUE THREAD

**Issue by MisakaOne** [JMBQ/URC#5]
![Screenshot_2023-06-01-19-18-28-836_com JMBQ URC jpg](https://github.com/JMBQ/URC/assets/108571772/c913f462-8d2e-498d-b5e8-1174619781a3)

**Comment by JMBQ** [comment]
等待更新，代码修改量很大，需要几天时间

**Comment by lzq1996ly** [comment]
> 等待更新，代码修改量很大，需要几天时间

请问降龙怎么开启
![Screenshot_2023-06-03-21-22-59-689_com JMBQ URC](https://github.com/JMBQ/URC/assets/132569859/f0cbfa46-464a-4244-9ae3-21a83c38a42d)

**Comment by JMBQ** [comment]
> > 等待更新，代码修改量很大，需要几天时间
> 
> 请问降龙怎么开启 <img alt="Screenshot_2023-06-03-21-22-59-689_com JMBQ URC" width="0" height="0" src="https://user-images.githubusercontent.com/132569859/243096772-f0cbfa46-464a-4244-9ae3-21a83c38a42d.jpg">

自行摸索

**Comment by brx0902** [comment]
降龙还是67位数那里吗，还是跟原来一样纯数字吗作者大大
