### ISSUE TITLE
No zygisk process found meaning

### ISSUE THREAD

**Issue by reinca** [JMBQ/URC#6]
Android 13
Honkai server: JP
Magisk version: 26.1
![image](https://github.com/JMBQ/URC/assets/10111468/4a22ea1a-1b43-4c0d-b42d-5d96375eda78)
![IMG_0825](https://github.com/JMBQ/URC/assets/10111468/136178ef-0f9b-493d-ae09-c0e698c9440c)

When I touch magic, no zygisk process found occurred

**Comment by JMBQ** [comment]
![IMG_20230610_170107.jpg](https://github.com/JMBQ/URC/assets/78288131/8e4778a7-16c0-4ced-b500-e5a9a1aa4101)

magisk setting, open it and reboot phone

**Comment by reinca** [comment]
I turned off Denylist and install Shamiko then work well in URC 1.3.9

![IMG_0828](https://github.com/JMBQ/URC/assets/10111468/e965b99a-c335-46be-a623-e8dacc2d9ee2)
But 1.4.0 failed same, remain log

**Comment by JMBQ** [comment]
I suggest to go to the official website to download the complete installation package to install and use instead of google play
