### ISSUE TITLE
Tw測試端

### ISSUE THREAD

**Issue by 8110044** [JMBQ/URC#7]
請求問題之討論
U.R.C.之降龍/Lk使用 - 修改config簡易方式.
延遲作用（10~40）其目的為何.
目前Tw端版號6.6.0使用U.R.C 1.4.0 ，進入電梯時常發生卡屏；解決辦法為使用U.R.C 1.3.9即可恢復使用、發生原因不明
感謝技術支持、萬分

**Comment by JMBQ** [comment]
LK是风险高的功能，不建议使用，所以不提供直接开启的方式。如果你一定要用，打开/data/data/packagename/files/config.ini, 里面有条config=的数字字符串，改它开启，自行摸索

延时使用默认10就好，老设备运行慢才需要增加等待时间

170 TW偶尔卡屏的问题，我觉得可能是你手机运存不够引起的，URC首页有显示多少G运存，可以发截图看下

140做了许多hook，139没有hook，运存消耗确实比139高，但安全性也比139高

**Comment by 8110044** [comment]
U.R.C. 1.3.9 (某原因無偵測內存)
![Screenshot_20230611_002333_VPhoneGaGa](https://github.com/JMBQ/URC/assets/136167743/00a03bef-cd6d-4501-bab4-050bc4efe51f)

U.R.C. 1.4.0 (成功偵測）
![Screenshot_20230611_002528_VPhoneGaGa](https://github.com/JMBQ/URC/assets/136167743/f48116d9-f942-45d7-804a-795fc164be7d)
以上為您答覆；並且理解Config使用方式/延遲說明
並且知悉（任何三方修改都必須承擔風險）的。
十分感謝您的提醒，也十分感謝您為此小問題抽空答覆！

**Comment by JMBQ** [comment]
我已经更新了README，应该对你有帮助

**Comment by 8110044** [comment]
Android13 64bit/台端Tw6.6.0
終數測試  / 返裝修正
:::目前供可建議小修正回饋:::
1_搭 U.R.C.1.4.0 電梯中卡屏仍在~（不排除使用方 硬/軟件基底問題）
2_搭 U.R.C.1.3.9 Start on LK = 魂斗羅模式 ~（自主新模式）
另外回覆..Tw端主程式默認商店原裝，不支持三方外連檔（會阻擋並提示來源問題）~
~以上
後輩技術不甚堪、小見略供使用交流
無論皆果、終感謝技術支持，在此萬分！

**Comment by JMBQ** [comment]
> Android13 64bit/台端Tw6.6.0
> 終數測試  / 返裝修正
> :::目前供可建議小修正回饋:::
> 1_搭 U.R.C.1.4.0 電梯中卡屏仍在~（不排除使用方 硬/軟件基底問題）
> 2_搭 U.R.C.1.3.9 Start on LK = 魂斗羅模式 ~（自主新模式）
> 
> 另外回覆..Tw端主程式默認商店原裝，不支持三方外連檔（會阻擋並提示來源問題）直連就是10Mb主程式 
> 了
> ~以上
> 後輩技術不甚堪、小見略供使用交流
> 無論皆果、終感謝技術支持，在此萬分！

是让你去官网下载整包，没让你下载第三方的安装包，你在play下载的是分包

139对分包生效是因为我做了特别处理，但不适用于6.7.0，等游戏更新时，你们会明白的
